QUESTION_SFT = """
As an expert driving assistant, analyze the 3-second driving video context and answer the question ONLY in the final frame.
Output format is <think_perception> </think_perception>\n<answer_perception> </answer_perception>\n<think_prediction> </think_prediction>\n<answer_prediction> </answer_prediction>\n<think_planning> </think_planning>\n<answer_planning> </answer_planning>. 
Perception answer consists of key object bounding box and category. Bounding box is a list of four numbers [x1, y1, x2, y2]. Key object categories include: car, bus, truck, bicycle, pedestrian, motorcycle.
Prediction answer consists of key object bounding box and future state. Key object future state includes stop, straight, right and left.
Planning answer consists of speed and path, speed includes keep, accelerate, deaccelerate, and stop. Path includes straight, right and left. 
Output the step-by-step Chain-of-Thought (CoT) reasoning process in <think> </think> tags and final answer in <answer> </answer> tags, respectively. 

For example, a correct answer format is like '<think_perception>Let me examine the image carefully to identify key objects and their coordinates. The key object categories to look for are car, bus, truck, bicycle, pedestrian, and motorcycle. The image size is 896x504, so I will determine the bounding box coordinates for each detected object.\n\n1. I observe a car on the left side of the image. Its approximate bounding box coordinates are:\n   - Top-left corner: (196, 266)\n   - Bottom-right corner: (340, 336)\n\n2. No other objects from the specified categories (bus, truck, bicycle, pedestrian, motorcycle) are visible in the image.\n\nThus, the only detected object is a car with the bounding box coordinates mentioned above.</think_perception>\n<answer_perception>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"label\": \"car\"}\n]\n```</answer_perception>\n<think_prediction>1. The key object in the scene is a car located at [196, 266, 340, 336].\n2. The car's current status is going straight, and it is not in the moving direction of the ego vehicle.\n3. The car's future state is predicted to remain going straight, as there is no indication of a change in its trajectory or behavior.\n4. The green traffic light in the scene does not directly affect the car's behavior since the car is not in the ego vehicle's path.\n5. Based on the video context, the car's future action is to continue going straight.</think_prediction>\n<answer_prediction>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"future_action\": \"straight\"}\n]\n```</answer_prediction>\n<think_planning>1. The ego vehicle is moving in the direction of the green traffic light, which signals to proceed.\n2. The car at [196, 266, 340, 336] is not in the ego vehicle's path and will not affect its movement.\n3. The ego vehicle's target action is to go straight, and the safe actions include maintaining the same speed or decelerating gradually.\n4. The video context indicates that accelerating and going straight is the most probable action for the ego vehicle based on the green traffic light.\n5. However, the planning answer provided suggests the ego vehicle should stop and go straight. This could be due to a potential hazard or a need to reassess the situation.\n6. Considering the low probability of collision and the green light, the ego vehicle should proceed cautiously, but the provided planning answer indicates stopping.</think_planning>\n<answer_planning>```json\n\t{\"speed\": \"stop\", \"path\": \"straight\"}\n```</answer_planning>'.
"""


QUESTION_RL = """
As an expert driving assistant, analyze the 3-second driving video context and answer the question ONLY in the final frame.
Output format is <think_perception> </think_perception>\n<answer_perception> </answer_perception>\n<think_prediction> </think_prediction>\n<answer_prediction> </answer_prediction>\n<think_planning> </think_planning>\n<answer_planning> </answer_planning>. 
Perception answer consists of key object bounding box and category. Bounding box is a list of four numbers [x1, y1, x2, y2]. Key object categories include: car, bus, truck, bicycle, pedestrian, motorcycle.
Prediction answer consists of key object bounding box and future state. Key object future state includes stop, straight, right and left.
Planning answer consists of speed and path, speed includes keep, accelerate, deaccelerate, and stop. Path includes straight, right and left. 
Output the step-by-step Chain-of-Thought (CoT) reasoning process in <think> </think> tags and final answer in <answer> </answer> tags, respectively. 

For example, a correct answer format is like '<think_perception>Let me examine the image carefully to identify key objects and their coordinates. The key object categories to look for are car, bus, truck, bicycle, pedestrian, and motorcycle. The image size is 896x504, so I will determine the bounding box coordinates for each detected object.\n\n1. I observe a car on the left side of the image. Its approximate bounding box coordinates are:\n   - Top-left corner: (196, 266)\n   - Bottom-right corner: (340, 336)\n\n2. No other objects from the specified categories (bus, truck, bicycle, pedestrian, motorcycle) are visible in the image.\n\nThus, the only detected object is a car with the bounding box coordinates mentioned above.</think_perception>\n<answer_perception>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"label\": \"car\"}\n]\n```</answer_perception>\n<think_prediction>1. The key object in the scene is a car located at [196, 266, 340, 336].\n2. The car's current status is going straight, and it is not in the moving direction of the ego vehicle.\n3. The car's future state is predicted to remain going straight, as there is no indication of a change in its trajectory or behavior.\n4. The green traffic light in the scene does not directly affect the car's behavior since the car is not in the ego vehicle's path.\n5. Based on the video context, the car's future action is to continue going straight.</think_prediction>\n<answer_prediction>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"future_action\": \"straight\"}\n]\n```</answer_prediction>\n<think_planning>1. The ego vehicle is moving in the direction of the green traffic light, which signals to proceed.\n2. The car at [196, 266, 340, 336] is not in the ego vehicle's path and will not affect its movement.\n3. The ego vehicle's target action is to go straight, and the safe actions include maintaining the same speed or decelerating gradually.\n4. The video context indicates that accelerating and going straight is the most probable action for the ego vehicle based on the green traffic light.\n5. However, the planning answer provided suggests the ego vehicle should stop and go straight. This could be due to a potential hazard or a need to reassess the situation.\n6. Considering the low probability of collision and the green light, the ego vehicle should proceed cautiously, but the provided planning answer indicates stopping.</think_planning>\n<answer_planning>```json\n\t{\"speed\": \"stop\", \"path\": \"straight\"}\n```</answer_planning>'.
"""

QUESTION_SFT_0606 = """
You are an expert driving assistant. As an expert driving assistant, analyze the 3-second driving video context and answer the perception, prediction and planning question in the final frame.
Output format is '<think_perception> </think_perception>\n<answer_perception> </answer_perception>\n<think_prediction> </think_prediction>\n<answer_prediction> </answer_prediction>\n<think_planning> </think_planning>\n<answer_planning> </answer_planning>'. 
Output the step-by-step Chain-of-Thought (CoT) reasoning process in <think> </think> tags and final answer in <answer> </answer> tags, respectively. 
"""



QUESTION_RL_0606 = """
You are an expert driving assistant. As an expert driving assistant, analyze the 3-second driving video context and answer the perception, prediction and planning question in the final frame.
Output format is '<think_perception> </think_perception>\n<answer_perception> </answer_perception>\n<think_prediction> </think_prediction>\n<answer_prediction> </answer_prediction>\n<think_planning> </think_planning>\n<answer_planning> </answer_planning>'. 
Output the step-by-step Chain-of-Thought (CoT) reasoning process in <think> </think> tags and final answer in <answer> </answer> tags, respectively. 
"""



QUESTION_SFT_0605 = """
As an expert driving assistant, analyze the 3-second driving video context and answer the question ONLY in the final frame.
Output format is <think_perception> </think_perception>\n<answer_perception> </answer_perception>\n<think_prediction> </think_prediction>\n<answer_prediction> </answer_prediction>\n<think_planning> </think_planning>\n<answer_planning> </answer_planning>. 
Perception answer consists of key object bounding box and category. Bounding box is a list of four numbers [x1, y1, x2, y2]. Key object categories include: car, bus, truck, bicycle, pedestrian, motorcycle.
Prediction answer consists of key object bounding box and future state. Key object future state includes stop, straight, right and left.
Planning answer consists of speed and path, speed includes keep, accelerate, deaccelerate, and stop. Path includes straight, right and left. 
Output the step-by-step Chain-of-Thought (CoT) reasoning process in <think> </think> tags and final answer in <answer> </answer> tags, respectively. 

For example, a correct answer format is like '<think_perception>Let me examine the image carefully to identify key objects and their coordinates. The key object categories to look for are car, bus, truck, bicycle, pedestrian, and motorcycle. The image size is 896x504, so I will determine the bounding box coordinates for each detected object.\n\n1. I observe a car on the left side of the image. Its approximate bounding box coordinates are:\n   - Top-left corner: (196, 266)\n   - Bottom-right corner: (340, 336)\n\n2. No other objects from the specified categories (bus, truck, bicycle, pedestrian, motorcycle) are visible in the image.\n\nThus, the only detected object is a car with the bounding box coordinates mentioned above.</think_perception>\n<answer_perception>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"label\": \"car\"}\n]\n```</answer_perception>\n<think_prediction>1. The key object in the scene is a car located at [196, 266, 340, 336].\n2. The car's current status is going straight, and it is not in the moving direction of the ego vehicle.\n3. The car's future state is predicted to remain going straight, as there is no indication of a change in its trajectory or behavior.\n4. The green traffic light in the scene does not directly affect the car's behavior since the car is not in the ego vehicle's path.\n5. Based on the video context, the car's future action is to continue going straight.</think_prediction>\n<answer_prediction>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"future_action\": \"straight\"}\n]\n```</answer_prediction>\n<think_planning>1. The ego vehicle is moving in the direction of the green traffic light, which signals to proceed.\n2. The car at [196, 266, 340, 336] is not in the ego vehicle's path and will not affect its movement.\n3. The ego vehicle's target action is to go straight, and the safe actions include maintaining the same speed or decelerating gradually.\n4. The video context indicates that accelerating and going straight is the most probable action for the ego vehicle based on the green traffic light.\n5. However, the planning answer provided suggests the ego vehicle should stop and go straight. This could be due to a potential hazard or a need to reassess the situation.\n6. Considering the low probability of collision and the green light, the ego vehicle should proceed cautiously, but the provided planning answer indicates stopping.</think_planning>\n<answer_planning>```json\n\t{\"speed\": \"stop\", \"path\": \"straight\"}\n```</answer_planning>'.
"""


QUESTION_RL_0605 = """
As an expert driving assistant, analyze the 3-second driving video context and answer the question ONLY in the final frame.
Output format is <think_perception> </think_perception>\n<answer_perception> </answer_perception>\n<think_prediction> </think_prediction>\n<answer_prediction> </answer_prediction>\n<think_planning> </think_planning>\n<answer_planning> </answer_planning>. 
Perception answer consists of key object bounding box and category. Bounding box is a list of four numbers [x1, y1, x2, y2]. Key object categories include: car, bus, truck, bicycle, pedestrian, motorcycle.
Prediction answer consists of key object bounding box and future state. Key object future state includes stop, straight, right and left.
Planning answer consists of speed and path, speed includes keep, accelerate, deaccelerate, and stop. Path includes straight, right and left. 
Output the step-by-step Chain-of-Thought (CoT) reasoning process in <think> </think> tags and final answer in <answer> </answer> tags, respectively. 

For example, a correct answer format is like '<think_perception>Let me examine the image carefully to identify key objects and their coordinates. The key object categories to look for are car, bus, truck, bicycle, pedestrian, and motorcycle. The image size is 896x504, so I will determine the bounding box coordinates for each detected object.\n\n1. I observe a car on the left side of the image. Its approximate bounding box coordinates are:\n   - Top-left corner: (196, 266)\n   - Bottom-right corner: (340, 336)\n\n2. No other objects from the specified categories (bus, truck, bicycle, pedestrian, motorcycle) are visible in the image.\n\nThus, the only detected object is a car with the bounding box coordinates mentioned above.</think_perception>\n<answer_perception>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"label\": \"car\"}\n]\n```</answer_perception>\n<think_prediction>1. The key object in the scene is a car located at [196, 266, 340, 336].\n2. The car's current status is going straight, and it is not in the moving direction of the ego vehicle.\n3. The car's future state is predicted to remain going straight, as there is no indication of a change in its trajectory or behavior.\n4. The green traffic light in the scene does not directly affect the car's behavior since the car is not in the ego vehicle's path.\n5. Based on the video context, the car's future action is to continue going straight.</think_prediction>\n<answer_prediction>```json\n[\n\t{\"bbox_2d\": [196, 266, 340, 336], \"future_action\": \"straight\"}\n]\n```</answer_prediction>\n<think_planning>1. The ego vehicle is moving in the direction of the green traffic light, which signals to proceed.\n2. The car at [196, 266, 340, 336] is not in the ego vehicle's path and will not affect its movement.\n3. The ego vehicle's target action is to go straight, and the safe actions include maintaining the same speed or decelerating gradually.\n4. The video context indicates that accelerating and going straight is the most probable action for the ego vehicle based on the green traffic light.\n5. However, the planning answer provided suggests the ego vehicle should stop and go straight. This could be due to a potential hazard or a need to reassess the situation.\n6. Considering the low probability of collision and the green light, the ego vehicle should proceed cautiously, but the provided planning answer indicates stopping.</think_planning>\n<answer_planning>```json\n\t{\"speed\": \"stop\", \"path\": \"straight\"}\n```</answer_planning>'.
"""




# QUESTION_TEMPLATE = """
# As an expert driving assistant, analyze the 3-second driving video context and answer the ego vehicle planning in the final frame.
# Output the reasoning process in <Perception_think> </Perception_think><Perception_answer> </Perception_answer><Prediction_think> </Prediction_think><Prediction_answer> </Prediction_answer><Planning_think> </Planning_think><Planning_answer> </Planning_answer> and final answer in <Planning_answer> </Planning_answer> tags. 
# Perception answer consists of key object bonding box, which is a list of four numbers [x1,y1,x2,y2].
# Prediction answer consists of key object future state, which includes stop, straight, right and left.
# Planning answer consists of speed and path, speed includes keep, accelerate, deaccelerate, and stop. Path includes straight, right and left. 

# For example, a correct answer format is like '<Perception_think>There are one objects in the scene. There is a car is located at [71, 191, 211, 268], noted by <car>[71,191,211,268]. <car>[71,191,211,268] current status is stationary. The weather is sunny. There is no traffic light.</Perception_think>
# <Perception_answer>[71, 191, 211, 268]</Perception_answer>
# <Prediction_think><car>[71,191,211,268] is not in the moving direction of the ego vehicle. The future state of <car>[71,191,211,268] is stationary. The ego vehicle considers <car>[71,191,211,268] most relevant to its decision. Except for the ego vehicle, no object would consider <car>[71,191,211,268] to be most relevant to its decision. There is no traffic light.</Prediction_think>
# <Prediction_answer>[71, 191, 211, 268]<stop></Prediction_answer>
# <Planning_think>The target action of the ego vehicle is go straight. In this scenario, the safe actions of the ego vehicle are keep going at the same speed, accelerate, and proceed. TIn this scenario, the dangerous actions of the ego vehicle are back up. <car>[71,191,211,268] is an object that the ego vehicle should consider in the current scene. The ego vehicle should keep going at the same speed based on <car>[71,191,211,268] because there is no safety issue, with a high probability. The probability of colliding with <car>[71,191,211,268] after the ego vehicle goes straight and maintains the same speed is low. No action taken by the ego vehicle will lead to a collision with <car>[71,191,211,268].</Planning_think>
# <Planning_answer>right, accelerate</Planning_answer>'.
# """


# QUESTION_TEMPLATE_1 = """
# As an expert driving assistant, analyze the 3-second driving video context and answer the ego vehicle planning in the final frame.
# Output the reasoning process in <Perception_think> </Perception_think><Perception_answer> </Perception_answer><Prediction_think> </Prediction_think><Prediction_answer> </Prediction_answer><Planning_think> </Planning_think><Planning_answer> </Planning_answer> and final answer in <Planning_answer> </Planning_answer> tags. 
# Planning answer consists of speed and path, speed includes keep, accelerate, deaccelerate, and stop. Path includes straight, right and left. 
# """

